version: "3"
services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app/
      - ./backend/node_modules/:/app/node_modules/
    networks:
      - default
    links:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9999:5432"
    networks:
      - default

  frontend:
    build: ./frontend
    depends_on:
      - postgres
      - backend
    environment:
      API_BASE_URL: http://localhost:3000/
    ports:
      - "1234:1234"
      - "1235:1235"
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules/:/app/node_modules/
    networks:
      - default
    links:
      - backend
networks:
  default:
