version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm start
    environment:
      PORT: 3000
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - default
    links:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '9999:5432'
    networks:
      - default
networks:
  default:
