insert into Categories (name) values ('Western');
insert into Categories (name) values ('Chinese');
insert into Categories (name) values ('Halal');
insert into Categories (name) values ('Asian');
insert into Categories (name) values ('Fast Food');
insert into Categories (name) values ('Local');
insert into Categories (name) values ('Beverages');
insert into Categories (name) values ('Burgers');
insert into Categories (name) values ('Seafood');
insert into Categories (name) values ('Noodles');
insert into Categories (name) values ('Healthy');
insert into Categories (name) values ('Breakfast');
insert into Categories (name) values ('Bubble Tea');
insert into Categories (name) values ('Chicken');
insert into Categories (name) values ('Dim Sum');
insert into Categories (name) values ('Indian');
insert into Categories (name) values ('Japanese');
insert into Categories (name) values ('Korean');
insert into Categories (name) values ('Ramen');
insert into Categories (name) values ('Vegetarian');
