insert into FoodItemBelongsTo (foodItemId, categoryName) values (153, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (499, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (121, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (388, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (121, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (517, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (650, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (108, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (399, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (239, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (519, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (899, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (695, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (779, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (606, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (651, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (178, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (866, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (686, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (702, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (684, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (994, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (287, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (465, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (829, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (587, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (620, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (235, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (456, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (634, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (80, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (384, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (995, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (578, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (274, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (487, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (691, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (148, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (735, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (930, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (921, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (781, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (547, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (848, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (968, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (463, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (617, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (652, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (108, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (834, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (246, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (70, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (223, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (535, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (185, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (503, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (98, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (166, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (684, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (999, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (506, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (465, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (147, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (939, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (427, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (615, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (951, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (355, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (551, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (448, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (465, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (951, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (434, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (867, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (185, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (95, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (190, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (271, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (138, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (878, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (535, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (472, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (829, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (975, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (243, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (953, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (504, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (145, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (888, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (858, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (66, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (100, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (711, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (409, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (925, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (724, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (619, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (691, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (479, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (305, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (450, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (598, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (231, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (413, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (828, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (311, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (35, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (622, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (225, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (56, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (392, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (856, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (327, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (807, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (138, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (300, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (884, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (593, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (799, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (83, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (565, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (926, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (537, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (160, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (663, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (35, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (465, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (245, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (657, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (857, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (204, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (596, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (857, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (400, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (55, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (381, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (331, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (261, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (520, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (978, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (639, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (674, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (792, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (829, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (424, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (548, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (753, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (168, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (134, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (532, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (989, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (100, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (378, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (595, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (525, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (227, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (149, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (16, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (939, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (514, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (17, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (240, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (170, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (5, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (902, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (545, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (149, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (833, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (833, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (457, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (542, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (157, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (484, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (83, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (451, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (116, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (543, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (139, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (330, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (358, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (530, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (48, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (137, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (857, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (898, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (136, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (538, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (289, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (927, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (968, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (686, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (527, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (84, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (309, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (169, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (783, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (408, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (82, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (969, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (967, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (886, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (823, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (12, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (108, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (944, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (557, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (62, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (221, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (393, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (721, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (635, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (294, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (172, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (57, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (163, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (621, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (127, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (867, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (540, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (485, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (937, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (554, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (799, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (571, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (272, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (934, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (991, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (609, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (72, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (404, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (552, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (220, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (543, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (256, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (726, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (158, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (513, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (276, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (316, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (981, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (791, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (577, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (864, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (282, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (665, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (511, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (980, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (230, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (768, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (251, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (671, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (962, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (929, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (949, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (944, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (143, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (889, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (61, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (650, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (754, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (404, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (162, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (106, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (951, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (888, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (219, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (194, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (27, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (331, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (824, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (244, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (955, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (771, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (567, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (174, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (662, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (610, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (342, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (309, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (839, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (780, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (56, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (990, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (473, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (386, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (547, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (497, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (766, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (291, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (688, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (722, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (223, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (831, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (438, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (844, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (88, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (561, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (89, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (671, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (83, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (769, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (67, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (389, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (781, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (79, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (336, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (45, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (221, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (856, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (694, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (154, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (22, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (272, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (458, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (107, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (433, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (879, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (35, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (336, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (623, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (884, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (503, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (239, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (780, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (676, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (772, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (330, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (517, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (413, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (594, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (168, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (985, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (142, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (674, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (404, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (214, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (902, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (316, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (257, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (288, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (540, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (439, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (871, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (485, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (932, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (176, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (439, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (147, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (743, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (721, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (889, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (516, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (147, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (568, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (225, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (978, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (179, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (513, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (822, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (893, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (809, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (787, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (374, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (13, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (752, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (417, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (865, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (254, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (201, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (502, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (187, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (88, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (517, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (755, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (752, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (759, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (966, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (86, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (395, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (802, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (649, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (13, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (157, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (90, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (89, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (413, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (451, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (134, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (625, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (785, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (53, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (364, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (273, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (312, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (96, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (629, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (795, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (665, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (812, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (77, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (729, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (168, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (747, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (407, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (692, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (436, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (282, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (333, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (650, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (52, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (92, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (430, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (558, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (332, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (854, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (98, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (700, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (701, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (850, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (709, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (544, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (334, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (397, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (180, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (545, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (801, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (768, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (734, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (430, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (716, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (793, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (486, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (164, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (923, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (183, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (314, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (979, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (405, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (140, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (615, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (704, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (311, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (581, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (941, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (302, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (984, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (472, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (874, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (338, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (226, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (686, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (527, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (401, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (476, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (629, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (361, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (260, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (889, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (356, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (33, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (414, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (242, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (252, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (166, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (628, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (347, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (960, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (634, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (642, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (639, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (29, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (836, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (463, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (519, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (293, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (213, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (52, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (890, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (975, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (328, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (792, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (534, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (761, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (375, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (4, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (368, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (586, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (114, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (981, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (416, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (854, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (44, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (889, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (207, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (143, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (488, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (326, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (286, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (256, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (640, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (323, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (540, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (419, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (396, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (463, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (521, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (622, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (623, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (454, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (178, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (878, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (178, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (645, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (503, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (827, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (682, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (907, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (895, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (345, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (611, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (742, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (240, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (247, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (828, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (598, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (273, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (286, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (733, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (530, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (199, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (189, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (666, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (358, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (188, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (173, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (440, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (484, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (900, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (23, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (666, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (434, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (516, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (316, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (337, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (121, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (302, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (960, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (879, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (920, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (240, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (298, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (246, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (916, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (825, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (67, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (846, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (714, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (700, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (194, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (760, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (353, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (592, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (761, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (275, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (616, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (486, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (131, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (99, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (931, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (279, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (382, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (231, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (27, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (935, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (534, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (822, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (580, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (821, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (313, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (541, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (464, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (313, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (791, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (333, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (696, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (615, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (432, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (948, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (54, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (426, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (293, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (799, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (203, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (303, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (220, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (786, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (374, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (753, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (470, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (263, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (759, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (85, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (646, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (469, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (202, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (783, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (51, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (43, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (562, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (408, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (942, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (833, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (512, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (713, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (129, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (794, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (720, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (905, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (137, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (707, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (619, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (699, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (999, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (665, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (915, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (262, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (262, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (551, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (11, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (741, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (427, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (982, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (287, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (364, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (348, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (263, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (428, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (843, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (919, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (172, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (984, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (911, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (746, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (972, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (429, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (1000, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (394, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (466, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (87, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (360, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (766, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (96, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (482, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (816, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (790, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (76, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (42, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (736, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (174, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (606, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (37, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (742, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (192, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (718, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (67, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (833, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (572, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (387, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (129, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (346, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (682, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (316, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (183, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (886, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (590, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (208, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (294, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (456, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (224, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (493, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (910, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (177, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (266, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (40, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (30, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (307, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (204, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (597, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (657, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (594, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (15, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (925, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (139, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (133, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (168, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (983, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (913, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (594, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (622, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (880, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (544, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (106, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (439, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (206, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (958, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (131, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (453, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (778, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (716, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (154, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (605, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (626, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (906, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (115, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (986, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (93, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (872, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (204, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (962, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (900, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (2, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (149, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (100, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (347, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (750, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (417, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (809, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (933, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (944, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (518, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (112, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (836, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (172, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (350, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (695, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (431, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (859, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (716, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (334, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (508, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (985, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (895, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (797, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (80, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (736, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (208, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (202, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (402, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (870, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (358, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (187, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (748, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (4, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (146, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (514, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (562, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (491, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (816, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (820, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (784, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (324, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (472, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (366, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (937, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (612, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (301, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (805, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (619, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (677, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (5, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (33, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (411, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (779, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (770, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (537, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (9, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (862, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (606, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (902, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (793, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (988, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (38, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (981, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (972, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (974, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (104, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (295, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (612, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (754, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (705, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (529, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (207, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (239, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (907, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (19, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (868, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (204, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (880, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (568, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (348, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (866, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (182, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (815, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (86, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (439, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (705, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (102, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (487, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (438, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (728, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (93, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (311, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (106, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (865, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (284, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (395, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (145, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (124, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (567, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (170, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (181, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (648, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (262, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (379, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (899, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (522, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (398, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (666, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (867, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (548, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (460, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (205, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (783, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (815, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (569, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (352, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (25, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (710, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (685, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (88, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (137, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (628, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (866, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (918, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (600, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (56, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (854, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (774, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (313, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (396, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (957, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (4, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (113, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (22, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (942, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (551, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (764, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (976, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (270, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (268, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (990, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (160, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (793, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (452, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (712, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (178, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (48, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (37, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (520, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (454, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (154, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (871, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (28, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (885, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (121, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (853, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (135, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (317, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (421, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (521, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (871, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (575, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (62, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (226, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (681, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (855, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (597, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (748, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (793, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (315, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (825, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (698, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (780, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (793, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (272, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (74, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (384, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (236, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (512, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (550, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (635, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (471, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (915, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (521, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (801, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (730, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (804, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (98, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (479, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (688, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (293, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (856, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (908, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (133, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (979, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (300, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (580, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (379, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (960, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (776, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (458, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (822, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (559, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (936, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (500, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (31, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (947, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (268, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (925, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (455, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (639, 'Indian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (707, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (905, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (211, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (233, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (721, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (93, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (96, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (944, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (555, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (88, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (849, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (226, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (233, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (623, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (265, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (701, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (346, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (230, 'Halal');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (485, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (359, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (351, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (171, 'Chicken');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (244, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (692, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (535, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (541, 'Vegetarian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (750, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (831, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (669, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (998, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (992, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (734, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (917, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (452, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (581, 'Ramen');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (927, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (261, 'Chinese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (437, 'Seafood');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (871, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (593, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (736, 'Fast Food');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (280, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (586, 'Noodles');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (13, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (255, 'Japanese');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (57, 'Dim Sum');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (781, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (514, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (765, 'Western');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (368, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (958, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (248, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (305, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (427, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (620, 'Local');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (81, 'Burgers');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (398, 'Beverages');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (831, 'Asian');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (934, 'Bubble Tea');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (613, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (86, 'Breakfast');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (278, 'Korean');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (988, 'Healthy');
insert into FoodItemBelongsTo (foodItemId, categoryName) values (215, 'Halal');
